app:
 openApi:
    server-url: http://localhost:8080
    server-version: 0.3.11
    server-title: Client API SIRENE EXEMPLE REST
 properties: 
  sirene:
   baseUri: https://api.insee.fr/api-sirene/3.11
   keyIntegration: pppppppp
