springdoc:
  version: '@springdoc.version@'
  api-docs:
    groups:
      enabled: true
  display-request-duration: true
  groups-order: ASC
  operationsSorter: method
  disable-swagger-default-url: true
  use-root-path: true
  path: /swagger-ui.html
  url: /api-docs.yaml


spring:
 config:
    import:
    - file:///etc/simple-sirene/application.yml
logging:
  config: file:/etc/simple-sirene/logback.xml
      
      