springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


spring:
 config:
    import:
    - file:///etc/simple-sirene/application.yml
logging:
  config: file:/etc/simple-sirene/logback.xml
      
      